### ISSUE TITLE
License change 📝

### ISSUE THREAD

**Issue by RDCH106** [jbarbadillo/pyFSM#2]
I think that GPL o LGPL are better choices because AGPL is license focused on software running over network:

https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License

> The Free Software Foundation has recommended that the GNU AGPLv3 be considered for any software that will commonly be run over a network.

**Comment by jbarbadillo** [comment]
And what about MIT?

**Comment by RDCH106** [comment]
It could be a option.

The more used licenses in Python libraries are MIT and LGPL.

I prefer LGPL because it is compatible with privative code and other licenses and it is mandatory give back and release the library updates.
